// Los 4 talleres del Pitch Deck (Propuesta de Valor). El conteo de cursos
// por categoría se calcula en Catalog.jsx a partir de COURSES, no aquí.
export const CATEGORIES = [
  { id:'redes-ia',       label:'📱 Redes Sociales & IA' },
  { id:'branding',       label:'🎨 Branding & Marca' },
  { id:'marketing',      label:'📈 Marketing Digital' },
  { id:'emprendimiento', label:'🚀 Emprendimiento Digital' },
];

// Los 4 talleres reales del Pitch Deck, ya con precio, descuento y horario de
// clase confirmados (antes quedaban en null "hasta que se confirme").
export const COURSES = [
  {
    id: 1,
    title: 'Redes Sociales & IA',
    cat: 'redes-ia',
    emoji: '📱',
    color: '#1a1035,#0d1628',
    instructor: 'Netwise Agencia',
    summary: 'Del contenido manual a la creación asistida por Inteligencia Artificial para multiplicar la productividad de marca.',
    labName: 'Social AI Lab™',
    description: 'Metodología de enseñanza práctica para producir y escalar una estrategia de redes sociales usando IA en cada etapa del proceso (investigación de tendencias, ideación, copywriting, producción visual/video y community management), aplicando modelos de atracción y conversión validados en marketing digital.',
    highlights: [
      'Estrategia y prompts: flujo continuo de copys y gráficos',
      'Automatización de publicación y respuesta en redes',
      'Proyecto final: calendario de 30 días activado con IA',
    ],
    badge: 'Nuevo',
    icon: 'sparkles',
    outcomeHeadline: 'Crear una estrategia de redes que conecte con tu audiencia y medir qué contenido funciona.',
    longDescription: [
      'Descubre como darle dirección a la presencia digital de tu marca. En este curso recorrerás la auditoría de tus canales, la creación de contenidos con apoyo de IA y las estrategias de social selling, con clases online en vivo y trabajo sobre tu propio proyecto.',
      'A lo largo de ocho semanas, conectarás lo que publicas con una audiencia y un objetivo. Desarrollarás un plan de contenidos, organizarás un recorrido de conversión y aprenderás a interpretar métricas para decidir qué mantener, probar o mejorar.',
    ],
    doableList: [
      'Analizar tus canales y tu competencia para identificar oportunidades de comunicación.',
      'Planificar contenidos y desarrollar guiones y piezas con apoyo de IA.',
      'Organizar un embudo en WhatsApp Business y medir el desempeño de tu estrategia.',
    ],
    scheduleDays: ['Lunes', 'Miércoles'],
    scheduleTime: '19:00-21:00',
    projectFinal: 'Plan de contenidos, funnel y dashboard social',
    price: 300,
    promoPercent: 25,
    duration: '8 semanas',
    level: 'Nivel básico',
    cardTag: 'Contenido & IA',
    cardTitle: ['Estrategias de', 'Redes Sociales'],
    cardDesc: 'Conecta estrategia, contenido con IA y social selling para hacer crecer tu presencia digital.',
  },
  {
    id: 2,
    title: 'Branding & Marca',
    cat: 'branding',
    emoji: '🎨',
    color: '#1a0d28,#28103a',
    instructor: 'Netwise Agencia',
    summary: 'Construcción de identidad de marca sólida: desde el propósito hasta el manual de aplicación para canales digitales.',
    labName: 'Brand Equity Lab™',
    description: 'Metodología de construcción de marca basada en el modelo CBBE de Kevin Keller, aplicada mediante análisis de casos reales y talleres 90% prácticos, donde cada participante construye su propio Brand Deck Ejecutivo sesión a sesión.',
    highlights: [
      'Propósito y territorio de marca',
      'Identidad visual y tono de comunicación',
      'Manual de marca para canales digitales',
    ],
    badge: 'Nuevo',
    icon: 'fingerprint',
    outcomeHeadline: 'Construir una marca con identidad propia y una experiencia coherente en cada punto de contacto.',
    longDescription: [
      'Construye una marca desde su estrategia hasta la forma en que se expresa y se vive. Trabajarás el propósito, la personalidad y el posicionamiento de tu proyecto, conectándolos con una identidad verbal y visual coherente.',
      'Durante ocho semanas de clases en vivo, avanzarás en tu plataforma y manual de marca. También explorarás sus puntos de contacto y prepararás un plan de lanzamiento para presentar una propuesta reconocible y consistente.',
    ],
    doableList: [
      'Definir el propósito, la personalidad y la propuesta de valor de tu marca.',
      'Organizar su identidad visual y tono de voz en un manual de marca.',
      'Diseñar sus puntos de contacto y preparar una estrategia de lanzamiento.',
    ],
    scheduleDays: ['Martes', 'Jueves'],
    scheduleTime: '19:00-21:00',
    projectFinal: 'Plataforma, manual y plan de lanzamiento de marca',
    price: 360,
    promoPercent: 25,
    duration: '8 semanas',
    level: 'Nivel básico',
    cardTag: 'Identidad & Diseño',
    cardTitle: ['Branding y', 'Gestión de Marcas'],
    cardDesc: 'Construye una identidad visual sólida y un manual de marca listo para tus canales digitales.',
  },
  {
    id: 3,
    title: 'Marketing Digital',
    cat: 'marketing',
    emoji: '📈',
    color: '#0d1a10,#102015',
    instructor: 'Netwise Agencia',
    summary: 'Estrategia y ejecución integral: Meta/Google Ads, SEO, automatizaciones y analítica para generar resultados.',
    description: 'Estrategia y ejecución integral de marketing digital: pauta en Meta y Google Ads, SEO, automatizaciones y analítica orientada a resultados.',
    highlights: [
      'Meta Ads y Google Ads de principio a fin',
      'SEO y automatizaciones de marketing',
      'Analítica y reportes con KPIs medibles',
    ],
    badge: 'Nuevo',
    icon: 'trending-up',
    outcomeHeadline: 'Planificar campañas digitales y usar los datos para mejorar tus resultados.',
    longDescription: [
      'Aprende a conectar estrategia, captación y medición en un plan de marketing digital. El curso reúne fundamentos de growth e inbound, posicionamiento en buscadores, publicidad digital y analítica para trabajar cada etapa del recorrido de tus clientes.',
      'En ocho semanas de clases en vivo, desarrollarás un embudo de conversión, propuestas de campañas y una página de captación. Usarás indicadores y tableros para analizar resultados y orientar la mejora de tus acciones.',
    ],
    doableList: [
      'Diseñar un embudo de captación con objetivos e indicadores definidos.',
      'Plantear acciones de SEO y campañas de búsqueda, conectadas con una página de captación.',
      'Construir un tablero de métricas para evaluar y optimizar tus campañas.',
    ],
    scheduleDays: ['Lunes', 'Miércoles'],
    scheduleTime: '21:00-23:00',
    projectFinal: 'Embudo, campañas y dashboard de marketing',
    price: 450,
    promoPercent: 25,
    duration: '8 semanas',
    level: 'Nivel básico',
    cardTag: 'Growth & Performance',
    cardTitle: ['Marketing', 'Digital desde 0'],
    cardDesc: 'Domina Meta/Google Ads, SEO y automatizaciones para generar resultados medibles.',
  },
  {
    id: 4,
    title: 'Emprendimiento Digital',
    cat: 'emprendimiento',
    emoji: '🚀',
    color: '#28100d,#3a1a10',
    instructor: 'Netwise Agencia',
    summary: 'De la idea al negocio validado: modelo Canvas, Producto Mínimo Viable (MVP) y plan de lanzamiento a 90 días.',
    description: 'Lleva tu idea a un negocio validado: modelo Canvas, Producto Mínimo Viable (MVP) y un plan de lanzamiento a 90 días.',
    highlights: [
      'Modelo de negocio Canvas',
      'Producto Mínimo Viable (MVP) validado en mercado',
      'Plan de lanzamiento a 90 días',
    ],
    badge: 'Nuevo',
    icon: 'rocket',
    outcomeHeadline: 'Validar tu idea, construir un MVP y preparar el lanzamiento de tu negocio digital.',
    longDescription: [
      'Transforma una idea en una propuesta de negocio que puedas poner a prueba. Aprenderás a investigar el problema que quieres resolver, definir tu modelo de negocio y construir una primera versión de tu producto digital con herramientas no-code y apoyo de IA.',
      'Durante ocho semanas de clases en vivo, trabajarás la validación, el desarrollo de tu producto mínimo viable y la preparación de su salida al mercado. Organizarás tu propuesta en un pitch con proyección financiera para comunicar cómo funcionaría tu negocio.',
    ],
    doableList: [
      'Validar el problema y la propuesta de valor de tu idea de negocio.',
      'Construir un producto mínimo viable con herramientas no-code.',
      'Preparar un plan de lanzamiento y un pitch con proyección financiera.',
    ],
    scheduleDays: ['Martes', 'Jueves'],
    scheduleTime: '21:00-23:00',
    projectFinal: 'MVP y pitch deck con proyección financiera',
    price: 480,
    promoPercent: 25,
    duration: '8 semanas',
    level: 'Nivel básico',
    cardTag: 'Negocios & Estrategia',
    cardTitle: ['Creación de', 'Negocios Digitales'],
    cardDesc: 'Lleva tu idea a un negocio validado con un MVP y un plan de lanzamiento a 90 días.',
  },
];

// Clases en vivo: se programan desde el panel de Docente (ver
// scheduleLiveSession en lib/db.js). En producción cada doc vive en la
// colección Firestore `liveSessions`.
export const LIVE_SESSIONS = [];
